### ISSUE TITLE
one platform build other not

### ISSUE THREAD

**Issue by holdfenytolvaj** [jupitex/node-libxml#13]
Hi,

sorry if I ask a noob question. 
I tried to install node-libxml on the docker:node:10 image, but for some reason it triggers the build and apparently the vendor directory is not included in the 4.1.1 version therefore the build fails on the target.

On the other hand on my computer there is no build is performed (no build directory) npm/yarn install finish without build and xml.node. What triggers the build and why is it needed / not needed ?
I've read a bit about it. But still have no idea how node-pre-gyp decides. And if I manually execute
```
node_modules/.bin/node-pre-gyp install
```
it fails to pull the precompiled as it is only exists for 4.0.0 (which is written not to be working on the readme.md)

(note: both are linux x64 and has the same node 10 & gyp version)

Thanks for any pointer

**Comment by MatthD** [comment]
Hi @holdfenytolvaj , if you try to install the `node_modules` on your host you will that on those new versions we have a `prebuild` folder . here there is all for linux/Mac/windows BUT only in 64 bits system.
I suppose docker:node is using a 32 bits linux so that it have to `build from source` and dependencies for building are missing (which is normal for a docker image which don't have the requirement for build)

I could take a look at it to see if I can build linux 32 version for dockers images

**Comment by holdfenytolvaj** [comment]
Hi, thanks for answering so quickly!

It is also 64bit. but does not worth the investigation if the vendor folder could be added.
It is missing because the package.json->files does not list it I believe.

Thanks a lot!

**Comment by MatthD** [comment]
Hi @holdfenytolvaj , 

Just one question, is the build failing on your docker ? Or this was just a general question to enhance & maybe rebuild.
I am currently trying on `docker:node:10` and it seems to use alpine & not really linux-64 so we need to generate alpine rebuild for docker .

I can manage to do it but It does not seems really easy to have rebuild manage specific linux platform :D

**Comment by MatthD** [comment]
I just published 4.1.2 with vendor folder and checked it build on docker:node:10, could you confirm it too @holdfenytolvaj ?

**Comment by holdfenytolvaj** [comment]
Hi, 

docker:node:10 is built on debian strech
https://github.com/nodejs/docker-node/blob/dbee85cde7c9d11d9df2d9305df4039942fc1ba9/10/stretch/Dockerfile
Thanks a lot! will try!

**Comment by holdfenytolvaj** [comment]
Hi, 

I'm not sure why is it, but now it takes the precompiled binary (even so no new binary you have added in the commit), 
but if I force the build that also works. 
So double happiness! 

Thanks a lot!!!
