### ISSUE TITLE
build fails for node v12

### ISSUE THREAD

**Issue by tuphampro** [jupitex/node-libxml#9]
Hello!

I am trying to use this package in a project with Nodejs version 12, which fails.
It works with Nodejs version 10. But is there any chance to get it running with Node 12?

**Comment by MatthD** [comment]
HI @tuphampro someoe has tried to PR modifications for node12 but it's not easy as pie, I do not have the time to work on it currently, will try in some weeks.

**Comment by MatthD** [comment]
Should now be working with node12
